package com.lucas.petshop.model;

import com.lucas.petshop.service.ProductAnimalTypeEnum;
import com.lucas.petshop.service.ProductTypeEnum;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity representing a product in the pet shop domain.
 *
 * <p>This class maps to the `tb_products` table and stores product-specific
 * properties such as name, type, brand, stock and pricing information.
 * Annotations from JPA and Hibernate control persistence behavior; Lombok's
 * {@code @Data} generates the usual boilerplate (getters/setters, toString,
 * equals and hashCode).</p>
 */
@Data
@Entity
@Table(name = "tb_products")
public class Product {

    // Primary key (auto-generated by the database)
    @Id
    @Column(name = "product_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Human-friendly name for the product. Required (not null) in the DB.
    @Column(name = "name", nullable = false)
    private String name;

    // Product category/type stored as a String representation of the application enum.
    // Using @Enumerated(EnumType.STRING) ensures the enum name is persisted rather
    // than the ordinal number (safer for schema evolution).
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private ProductTypeEnum type;

    // Target animal type for which this product is intended (e.g. DOG, CAT).
    // Also persisted as the enum's name string.
    @Enumerated(EnumType.STRING)
    @Column(name = "animal_type", nullable = false)
    private ProductAnimalTypeEnum animalType;

    // Brand or manufacturer name
    @Column(name = "brand", nullable = false)
    private String brand;

    // Long-form description of the product (user-facing text)
    @Column(name = "description", nullable = false)
    private String description;

    // Current inventory stock quantity for this product
    @Column(name = "stock", nullable = false)
    private Integer stock;

    // Retail price for the product (use a monetary type/strategy if needed in future)
    @Column(name = "price", nullable = false)
    private BigDecimal price;

    // Size or weight metric for the product (units depend on domain conventions)
    @Column(name = "size_weight", nullable = false)
    private Double sizeWeight;

    // Timestamp when the product was created. Auto-populated by Hibernate.
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    // Timestamp of the last update to this product. Auto-updated by Hibernate.
    @UpdateTimestamp
    @Column(name = "last_update")
    private LocalDateTime lastUpdate;

    // Soft-delete flag: when true the product is considered logically deleted
    // and should typically be excluded from normal queries.
    @Column(name = "deleted_product", nullable = false)
    private Boolean deletedProduct = false;
}
